apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/miloofcroton/mern-starter:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/miloofcroton/mern-starter:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: mern-starter
        chartPath: charts/mern-starter
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/miloofcroton/mern-starter"
          image.tag: "{{.DIGEST_HEX}}"
